export const pokemonData = [
  {
    id: "9580da84-0966-4c58-9b63-10a2f05926d7",
    name: "Pikachu",
    height: null,
    weight: null,
    hp: 9,
    image: "imagen",
    attack: 8,
    defense: 87,
    speed: null,
    types: [],
    created: true,
  },
  {
    id: 1,
    name: "bulbasaur",
    height: 7,
    weight: 69,
    hp: 45,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg",
    attack: 49,
    defense: 49,
    speed: 45,
    types: ["grass", "poison"],
    created: false,
  },
  {
    id: 2,
    name: "ivysaur",
    height: 10,
    weight: 130,
    hp: 60,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
    attack: 62,
    defense: 63,
    speed: 60,
    types: ["grass", "poison"],
    created: false,
  },
  {
    id: 3,
    name: "venusaur",
    height: 20,
    weight: 1000,
    hp: 80,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/3.svg",
    attack: 82,
    defense: 83,
    speed: 80,
    types: ["grass", "poison"],
    created: false,
  },
  {
    id: 4,
    name: "charmander",
    height: 6,
    weight: 85,
    hp: 39,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg",
    attack: 52,
    defense: 43,
    speed: 65,
    types: ["fire"],
    created: false,
  },
  {
    id: 5,
    name: "charmeleon",
    height: 11,
    weight: 190,
    hp: 58,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/5.svg",
    attack: 64,
    defense: 58,
    speed: 80,
    types: ["fire"],
    created: false,
  },
  {
    id: 6,
    name: "charizard",
    height: 17,
    weight: 905,
    hp: 78,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg",
    attack: 84,
    defense: 78,
    speed: 100,
    types: ["fire", "flying"],
    created: false,
  },
  {
    id: 7,
    name: "squirtle",
    height: 5,
    weight: 90,
    hp: 44,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg",
    attack: 48,
    defense: 65,
    speed: 43,
    types: ["water"],
    created: false,
  },
  {
    id: 8,
    name: "wartortle",
    height: 10,
    weight: 225,
    hp: 59,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/8.svg",
    attack: 63,
    defense: 80,
    speed: 58,
    types: ["water"],
    created: false,
  },
  {
    id: 9,
    name: "blastoise",
    height: 16,
    weight: 855,
    hp: 79,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/9.svg",
    attack: 83,
    defense: 100,
    speed: 78,
    types: ["water"],
    created: false,
  },
  {
    id: 10,
    name: "caterpie",
    height: 3,
    weight: 29,
    hp: 45,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/10.svg",
    attack: 30,
    defense: 35,
    speed: 45,
    types: ["bug"],
    created: false,
  },
  {
    id: 11,
    name: "metapod",
    height: 7,
    weight: 99,
    hp: 50,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/11.svg",
    attack: 20,
    defense: 55,
    speed: 30,
    types: ["bug"],
    created: false,
  },
  {
    id: 12,
    name: "butterfree",
    height: 11,
    weight: 320,
    hp: 60,
    image:
      "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/12.svg",
    attack: 45,
    defense: 50,
    speed: 70,
    types: ["bug", "flying"],
    created: false,
  },
];
