//pokemons
export const actionTypes = {
  GET_POKEMONS: "GET_POKEMONS",
  GET_POKEMON_BY_ID: "GET_POKEMON_BY_ID",
  GET_POKEMON_BY_NAME: "GET_POKEMON_BY_NAME",
  GET_POKEMONS_FROM_API: "GET_POKEMONS_FROM_API",

  CLOSE_POKEMON: "CLOSE_POKEMON",

  POST_POKEMON: "POST_POKEMON",
  POST_POKEMON_FROM_API: "POST_POKEMON_FROM_API",
  PUT_POKEMON: "PUT_POKEMON",
  DEL_POKEMON: "DEL_POKEMON",

  APPLY_FILTERS: "APPLY_FILTERS",
  APPLY_MULTIPLE_FILTERS: "APPLY_MULTIPLE_FILTERS",
  CLEAR_FILTERS: "CLEAR_FILTERS",

  CLEAR_POKEMON: "CLEAR_POKEMON",

  //pagination
  SET_PAGINATION_DATA: "SET_PAGINATION_DATA",
  SET_USER_PAGINATION_DATA: "SET_USER_PAGINATION_DATA",

  //types
  GET_TYPES: "GET_TYPES",
  GET_TYPES_LOCALSTORE: "GET_TYPES_LOCALSTORE",

  //footer Message
  SET_APP_STATUS: "SET_APP_STATUS",
  UPDATE_APP_STATUS: "UPDATE_APP_STATUS",
  ADD_MESSAGE: "ADD_MESSAGE",
  DELETE_MESSAGE: "DELETE_MESSAGE",
  UPDATE_MESSAGE: "UPDATE_MESSAGE",
};

// //pokemons
// export const GET_POKEMONS = "GET_POKEMONS";
// export const GET_POKEMON_BY_ID = "GET_POKEMON_BY_ID";
// export const GET_POKEMON_BY_NAME = "GET_POKEMON_BY_NAME";

// export const POST_POKEMON = "POST_POKEMON";
// export const PUT_POKEMON = "PUT_POKEMON";
// export const DEL_POKEMON = "DEL_POKEMON";

// export const FILTER_BY_SOURCE = "FILTER_BY_SOURCE";

// //pagination
// export const SET_PAGINATION_DATA = "SET_PAGINATION_DATA";
// export const SET_USER_PAGINATION_DATA = "SET_USER_PAGINATION_DATA";

// //types
// export const GET_TYPES = "GET_TYPES";
